version: 0.2

env:
  variables:
    AWS_ACCOUNT_ID: <aws-account-id>
    AWS_DEFAULT_REGION: eu-west-1
    IMAGE_REPO_PREFIX: rustic/
    IMAGE_REPO_BASE: rustic/app
    IMAGE_TAG: 0.1.0-SNAPSHOT
    RUST_VERSION: 1.52.1
    DISTROLESS_TAG: nonroot

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo Build started on $(date)
      - docker pull $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/${IMAGE_REPO_PREFIX}rust:$RUST_VERSION
      - docker tag $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/${IMAGE_REPO_PREFIX}rust:$RUST_VERSION ${IMAGE_REPO_PREFIX}rust:$RUST_VERSION
      - docker pull $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/${IMAGE_REPO_PREFIX}gcr.io/distroless/cc-debian10:$DISTROLESS_TAG
      - docker tag $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/${IMAGE_REPO_PREFIX}gcr.io/distroless/cc-debian10:$DISTROLESS_TAG ${IMAGE_REPO_PREFIX}gcr.io/distroless/cc-debian10:$DISTROLESS_TAG
      - docker pull $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_BASE-core-compiled:previous || docker tag ${IMAGE_REPO_PREFIX}rust:$RUST_VERSION $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_BASE-core-compiled:previous
      - docker tag $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_BASE-core-compiled:previous $IMAGE_REPO_BASE-core-compiled:previous
      - docker rmi $IMAGE_REPO_BASE-core-compiled:next || true
      - cp etc/settings-sample+build.sh etc/settings-local.sh
      - bin/create-local-settings.sh
      - echo Generating module with trusted keys
      - bin/generate-module-for-trusted-keys.sh -v
      - echo Building the Docker image...
      - docker build --tag $IMAGE_REPO_BASE-core-compiled:next -f docker/app/Dockerfile-compile .
      - docker build --tag $IMAGE_REPO_BASE-core:$IMAGE_TAG -f docker/app/Dockerfile-distribution docker/app
      - docker rmi $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_BASE-core-compiled:previous
      - docker tag $IMAGE_REPO_BASE-core-compiled:next $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_BASE-core-compiled:previous
      - docker tag $IMAGE_REPO_BASE-core:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_BASE-core:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on $(date)
      - echo Pushing the Docker images...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_BASE-core-compiled:previous
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_BASE-core:$IMAGE_TAG