apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: axon-server-eventdata-ebs-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 4Gi