apiVersion: v1
kind: Service
metadata:
  name: axon-server
  labels:
    {{- include "axonserver.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8024
      protocol: TCP
      name: http
    - port: 8124
      targetPort: 8124
      protocol: TCP
      name: grpc
  selector:
    {{- include "axonserver.selectorLabels" . | nindent 4 }}
