apiVersion: v1
kind: Service
metadata:
  name: {{ include "proxy.fullname" . }}
  labels:
    {{- include "proxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
    - port: 8124
      targetPort: 8124
      protocol: TCP
      name: grpc
  selector:
    {{- include "proxy.selectorLabels" . | nindent 4 }}
