apiVersion: v1
kind: Service
metadata:
  name: rustic-command-api
  labels:
    {{- include "monolith.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8181
      protocol: TCP
      name: grpc
  selector:
    {{- include "monolith.selectorLabels" . | nindent 4 }}
