apiVersion: v1
kind: Service
metadata:
  labels:
    app: elastic-search
  name: elastic-search
  namespace: ${ENSEMBLE_NAME}-test
spec:
  ports:
  - name: http
    port: 9200
    protocol: TCP
    targetPort: 9200
  - name: transport
    port: 9300
    protocol: TCP
    targetPort: 9300
  selector:
    app: elasticsearch-master
    chart: elasticsearch
    release: elasticsearch
  type: ClusterIP
